import numpy as np
import pdb

Id2Obj = {
    0: 'free',
    1: 'cellphone',
    2: 'mouse',
    3: 'keyboard',
    4: 'bottle',
    5: 'hair-dryer',
    6: 'Tetra-Pak',
    7: 'shoes',
    8: 'cup',
    9: 'instant-package',
    10: 'coffee-machine',
    11: 'wallet',
    12: 'pad',
    13: 'doorknob',
    14: 'backpack',
    15: 'laptop-keyboard',
    16: 'laptop',
    17: 'glasses',
    18: 'keys',
    19: 'toothbrush',
    20: 'toothpaste',
    21: 'remote-controller',
    22: 'socks',
    23: 'phone-charger',
    24: 'fridge',
    25: 'towel',
    26: 'bowl',
    27: 'chopsticks',
    28: 'spoon',
    29: 'lamp',
    30: 'headphone',
    31: 'book',
    32: 'clothes',
    33: 'pen',
    34: 'pen-case',
    35: 'water-dispenser',
    36: 'joystick',
    37: 'helmet',
    38: 'garbage',
    39: 'racket',
    40: 'banknote',
    41: 'detergent',
    42: 'laundry-basket',
    43: 'washing-machine',
    44: 'broom',
    45: 'swab',
    46: 'notebook',
    47: 'water-tap',
    48: 'comb',
    49: 'washbowl'
}

Obj = {}
for id in Id2Obj.items():
    Obj[id[1]] = id[0]

